/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author sugar
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn1Salir = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn2Consulta = new javax.swing.JRadioButtonMenuItem();
        mn2Modifica = new javax.swing.JRadioButtonMenuItem();
        mn2Listado = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mn3Vender = new javax.swing.JRadioButtonMenuItem();
        mn3Reporte = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mn4Desto = new javax.swing.JRadioButtonMenuItem();
        mn4Obsq = new javax.swing.JRadioButtonMenuItem();
        mn4CantOpt = new javax.swing.JRadioButtonMenuItem();
        mn4Premio = new javax.swing.JRadioButtonMenuItem();
        mn5Ayuda = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maletas S.A.");
        setBackground(new java.awt.Color(255, 255, 204));

        mn1Salir.setText("Archivo");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Salir");
        mn1Salir.add(jRadioButtonMenuItem1);

        jMenuBar1.add(mn1Salir);

        jMenu2.setText("Mantenimiento");

        mn2Consulta.setSelected(true);
        mn2Consulta.setText("Consultar maleta");
        jMenu2.add(mn2Consulta);

        mn2Modifica.setSelected(true);
        mn2Modifica.setText("Modificar maleta");
        jMenu2.add(mn2Modifica);

        mn2Listado.setSelected(true);
        mn2Listado.setText("Listar maletas");
        jMenu2.add(mn2Listado);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ventas");

        mn3Vender.setSelected(true);
        mn3Vender.setText("Vender");
        mn3Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn3VenderActionPerformed(evt);
            }
        });
        jMenu3.add(mn3Vender);

        mn3Reporte.setSelected(true);
        mn3Reporte.setText("Generar reportes");
        mn3Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn3ReporteActionPerformed(evt);
            }
        });
        jMenu3.add(mn3Reporte);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configuración");

        mn4Desto.setSelected(true);
        mn4Desto.setText("Configurar descuentos");
        jMenu4.add(mn4Desto);

        mn4Obsq.setSelected(true);
        mn4Obsq.setText("Configurar obsequio");
        jMenu4.add(mn4Obsq);

        mn4CantOpt.setSelected(true);
        mn4CantOpt.setText("Configurar cantidad óptima de maletas vendidas");
        jMenu4.add(mn4CantOpt);

        mn4Premio.setSelected(true);
        mn4Premio.setText("Configurar premio sorpresa");
        jMenu4.add(mn4Premio);

        jMenuBar1.add(jMenu4);

        mn5Ayuda.setText("Ayuda");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Acerca de la tienda");
        mn5Ayuda.add(jRadioButtonMenuItem4);

        jMenuBar1.add(mn5Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn3VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn3VenderActionPerformed
        FrmVender vender= new FrmVender();
        vender.setVisible(true);
    }//GEN-LAST:event_mn3VenderActionPerformed

    private void mn3ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn3ReporteActionPerformed
        FrmGenerarReporte reporte = new FrmGenerarReporte();
        reporte.setVisible(true);
    }//GEN-LAST:event_mn3ReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JMenu mn1Salir;
    private javax.swing.JRadioButtonMenuItem mn2Consulta;
    private javax.swing.JRadioButtonMenuItem mn2Listado;
    private javax.swing.JRadioButtonMenuItem mn2Modifica;
    private javax.swing.JRadioButtonMenuItem mn3Reporte;
    private javax.swing.JRadioButtonMenuItem mn3Vender;
    private javax.swing.JRadioButtonMenuItem mn4CantOpt;
    private javax.swing.JRadioButtonMenuItem mn4Desto;
    private javax.swing.JRadioButtonMenuItem mn4Obsq;
    private javax.swing.JRadioButtonMenuItem mn4Premio;
    private javax.swing.JMenu mn5Ayuda;
    // End of variables declaration//GEN-END:variables
}
